SELECT FS.CASEID,
       FS.SUBSYSID,
       FS.STEPID,
       FS.SUMMARY,
       FS.LABEL,
       FS.OWNER,
       FS.CLIENT,
       (SELECT STARTTIME From FLOWINCIDENT Where CASEID = FS.CASEID) AS CASESTTIME,
       FS.STARTTIME,
       UI.USERNAME,
       (SELECT SHORTSSNAME FROM SUBSYS_CODE WHERE SUBSYSID = FS.SUBSYSID) AS SYSNAME,
       (SELECT FVERSION From FLOWINCIDENT Where CASEID = FS.CASEID) AS FVERSION
  FROM FLOWSTEP FS
  LEFT OUTER JOIN USERINFO UI ON FS.OWNER = UI.STAFFID
 WHERE FS.CLIENT = 'S062285'/*Input StaffID*/
   AND FS.STATUS = '1'
   And (BRID = '149' Or BRID = '000')/*Input Brid*/
 ORDER BY FS.STARTTIME DESC;
