USE [OBStyleService]
GO

/****** Object:  UserDefinedFunction [dbo].[fnTABLE查詢]    Script Date: 2022/7/18 下午 01:49:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[fnTABLE查詢](@TABLE_NAME VARCHAR(50))
RETURNS @RETURN_TABLE TABLE
(
    表格名稱 VARCHAR(100),
    PK CHAR(1),
	欄位名稱 VARCHAR(100),
	資料型別 VARCHAR(50),
	長度 VARCHAR(50),
	預設值 VARCHAR(500),
	允許空值 CHAR(1),
	欄位描述 NVARCHAR(MAX)
)
AS
BEGIN
------------------------------------------------------
INSERT INTO @RETURN_TABLE(表格名稱, PK, 欄位名稱, 資料型別, 長度, 預設值, 允許空值, 欄位描述)
SELECT A.TABLE_SCHEMA +'.'+A.TABLE_NAME AS 表格名稱
    ,ISNULL((
        SELECT N'Y' 
		FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TAB, INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE COL 
        WHERE COL.CONSTRAINT_NAME = TAB.CONSTRAINT_NAME
		AND COL.TABLE_NAME = TAB.TABLE_NAME
		AND CONSTRAINT_TYPE = 'PRIMARY KEY'
		AND COL.TABLE_NAME = B.TABLE_NAME
		AND COL.COLUMN_NAME = B.COLUMN_NAME
    ), '') AS PK
	,B.COLUMN_NAME                         AS 欄位名稱   
	,B.DATA_TYPE                           AS 資料型別   
	,ISNULL(B.CHARACTER_MAXIMUM_LENGTH,'') AS 長度   
	,ISNULL(B.COLUMN_DEFAULT,'')           AS 預設值   
	,CASE B.IS_NULLABLE WHEN 'YES' THEN N'Y' ELSE '' END AS 允許空值   
    ,ISNULL((
		SELECT CONVERT(VARCHAR(MAX), VALUE)
		FROM FN_LISTEXTENDEDPROPERTY (NULL, 'SCHEMA', A.TABLE_SCHEMA, 'TABLE', A.TABLE_NAME, 'COLUMN', DEFAULT)   
		WHERE
		NAME='MS_DESCRIPTION' 
		AND OBJTYPE='COLUMN' 
		AND OBJNAME COLLATE CHINESE_TAIWAN_STROKE_CI_AS = B.COLUMN_NAME
	), '') AS 欄位描述   
FROM INFORMATION_SCHEMA.TABLES  A   
LEFT JOIN INFORMATION_SCHEMA.COLUMNS B ON A.TABLE_NAME = B.TABLE_NAME   
WHERE TABLE_TYPE='BASE TABLE' AND A.TABLE_NAME=@TABLE_NAME
ORDER BY A.TABLE_NAME , B.ORDINAL_POSITION 

RETURN
------------------------------------------------------
END
GO


